replicaCount: 1

env:
  - name: ASPNETCORE_HTTP_PORTS
    value: "6080"

image:
  repository: leferbadck/meteolive
  tag: 1.0.7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6080

resources: {}
