replicaCount: 1

env:
  - name: ASPNETCORE_HTTP_PORTS
    value: "6080"

image:
  repository: leferbadck/meteolive
  tag: 1.0.20
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 6080
  nodePort: 30080

resources: {}
